boxes = [
  { :name => "SCCM-DC",  :ip => "{{ip_range}}.10", :box => "jborean93/WindowsServer2019", :cpus => 2, :mem => 4000, :os => "windows"},
  { :name => "SCCM-MECM" , :ip => "{{ip_range}}.11", :box => "jborean93/WindowsServer2019", :cpus => 2, :mem => 4000, :os => "windows"},
  { :name => "SCCM-MSSQL", :ip => "{{ip_range}}.12", :box => "jborean93/WindowsServer2019", :cpus => 2, :mem => 4000, :os => "windows"},
  { :name => "SCCM-CLIENT",  :ip => "{{ip_range}}.13", :box => "jborean93/WindowsServer2019", :cpus => 2, :mem => 4000, :os => "windows"},
]

Vagrant.configure("2") do |config|

  config.vm.provider :libvirt do |libvirt|
    libvirt.qemu_use_session = false
  end

  boxes.each do |box|
    config.vm.define box[:name] do |cfg|
      cfg.vm.box = box[:box]
      cfg.vm.hostname = box[:name]
      cfg.vm.boot_timeout = 600
      cfg.vm.communicator = "winrm"
      cfg.winrm.basic_auth_only = true
      cfg.winrm.timeout = 300
      cfg.winrm.retry_limit = 20
      # Management network for internet access (automatic DHCP)
      cfg.vm.network :private_network, type: "dhcp"
      # Lab network for internal communication
      cfg.vm.network :private_network, ip: box[:ip], libvirt__network_name: "goad-network"

      cfg.vm.provider :libvirt do |libvirt|
        libvirt.memory = box[:mem]
        libvirt.cpus = box[:cpus]
        libvirt.driver = "kvm"
      end

      cfg.vm.provision "shell", inline: <<-SHELL
        Get-LocalUser -Name vagrant | Set-LocalUser -Password (Convertto-SecureString -AsPlainText "vagrant" -Force)
      SHELL
    end
  end
end