boxes = [
  { :name => "NHA-DC01",   :ip => "{{ip_range}}.10", :box => "jborean93/WindowsServer2019", :os => "windows", :cpus => 2, :mem => 3000},
  { :name => "NHA-DC02",   :ip => "{{ip_range}}.20", :box => "jborean93/WindowsServer2019", :os => "windows", :cpus => 2, :mem => 3000},
  { :name => "NHA-SRV01",  :ip => "{{ip_range}}.21", :box => "jborean93/WindowsServer2019", :os => "windows", :cpus => 2, :mem => 5000},
  { :name => "NHA-SRV02",  :ip => "{{ip_range}}.22", :box => "jborean93/WindowsServer2019", :os => "windows", :cpus => 2, :mem => 5000},
  { :name => "NHA-SRV03",  :ip => "{{ip_range}}.23", :box => "jborean93/WindowsServer2019", :os => "windows", :cpus => 2, :mem => 3000}
]

Vagrant.configure("2") do |config|

  config.vm.provider :libvirt do |libvirt|
    libvirt.qemu_use_session = false
  end

  boxes.each do |box|
    config.vm.define box[:name] do |cfg|
      cfg.vm.box = box[:box]
      cfg.vm.hostname = box[:name]
      cfg.vm.boot_timeout = 600
      cfg.vm.communicator = "winrm"
      cfg.winrm.basic_auth_only = true
      cfg.winrm.timeout = 300
      cfg.winrm.retry_limit = 20
      # Management network for internet access (automatic DHCP)
      cfg.vm.network :private_network, type: "dhcp"
      # Lab network for internal communication
      cfg.vm.network :private_network, ip: box[:ip], libvirt__network_name: "goad-network"

      cfg.vm.provider :libvirt do |libvirt|
        libvirt.memory = box[:mem]
        libvirt.cpus = box[:cpus]
        libvirt.driver = "kvm"
      end

      cfg.vm.provision "shell", inline: <<-SHELL
        Get-LocalUser -Name vagrant | Set-LocalUser -Password (Convertto-SecureString -AsPlainText "vagrant" -Force)
      SHELL
    end
  end
end